on: push
jobs:
  proto_doc:
    runs-on: ubuntu-latest
    steps:
      # Protocol Buffers Install
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      # Protoc-gen-doc Install
      - name: Install Protoc-gen-doc
        run: |
          go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
      # Make for Document Dir
      - name: Make Doc-directory
        run: mkdir -p docs
      # Target Checkout
      - name: Target Checkout
        uses: actions/checkout@v2
      # Generate Doc 
      - name: Generate Doc
        run: |
          find . -type f -name "*.proto" | while read PROTO; do
            echo ${PROTO}
            if [ ${PROTO##*.} == "proto" ]; then
              protoc --doc_out=./docs --doc_opt=html,${PROTO%.*}.html ${PROTO}
              protoc --doc_out=./docs --doc_opt=markdown,${PROTO%.*}.md ${PROTO}
            fi
          done
      # Document Commit 
      - name: Document commit
        run: |
          git config user.name github-actions
          git config user.email action@github.com
          git add .
          git commit -m "proto doc generated" || echo "No changes to commit"
          git push
          git pull origin main
